/**
 * demoData.ts — clearly-labeled demonstration dataset.
 *
 * PRISM works out of the box even when the live backend is unreachable or
 * unconfigured (no Firebase / Gemini / Redis credentials). In that case the
 * UI switches to DEMO DATA MODE and renders this dataset so every view
 * (feed, map, globe, bias comparison, debate, business) is fully explorable.
 *
 * These articles are GENERIC synthetic examples — they are never presented as
 * real news, and the UI badges them as demo data. When the backend is live,
 * real RSS-ingested articles replace this dataset entirely.
 */

import { Article, Source } from '../types';

const MINUTES = 60 * 1000;
const HOURS = 60 * MINUTES;
const DAYS = 24 * HOURS;

const now = Date.now();

// ---------------------------------------------------------------------------
// Per-article multi-agent debate analyses (progressive / conservative /
// omission / moderator verdict). Keyed by article id so the Verification
// Modal shows unique, article-specific analysis instead of one canned block.
// ---------------------------------------------------------------------------

interface DebateAnalysis {
  progressive: string;
  conservative: string;
  omissionFocused: string;
  moderatorVerdict: string;
  confidence: number;
}

const debateFor = (topic: string, progressive: string, conservative: string, omission: string, verdict: string, confidence = 0.78): DebateAnalysis => ({
  progressive,
  conservative,
  omissionFocused: omission,
  moderatorVerdict: verdict,
  confidence,
});

const debates: Record<string, DebateAnalysis> = {
  // Central bank / rates
  'demo-cb-1': debateFor(
    'central bank rate decisions',
    'A progressive reading emphasizes that tightening cycles fall hardest on wage earners and renters, and that the central bank should pair rate policy with targeted relief for vulnerable households.',
    'A conservative reading stresses that credible, independent monetary policy is the backbone of price stability, and that second-guessing the bank risks entrenching inflation expectations.',
    'Coverage omits the asymmetric impact of rate changes across income brackets and the pass-through lags that determine whether this decision actually cools demand.',
    'The article is broadly accurate but frames the decision through an institutional lens; the omitted distributional analysis matters for assessing real-world impact. Confidence is moderate because the underlying data is still rolling in.'
  ),
  'demo-cb-2': debateFor(
    'inflation data releases',
    'Progressives note the release shows goods disinflation but services inflation persists, pointing to housing costs and corporate margin behavior as under-examined drivers.',
    'Conservatives read the print as evidence that restraint is working and warn that premature easing would repeat the policy mistakes of prior cycles.',
    'The headline glosses over seasonality adjustments and the fact that core measures diverged sharply from the topline number.',
    'The reporting is factually sound but headline-driven; the divergence between core and headline inflation is the story that deserves the attention.'
  ),
  // Semiconductors / supply chains
  'demo-semi-1': debateFor(
    'semiconductor export controls',
    'Progressive analysis welcomes the export regime as overdue industrial policy that rebalances strategic dependencies and funds domestic manufacturing capacity.',
    'Conservative analysis warns that export controls distort markets, raise costs for downstream consumers, and invite retaliatory restrictions that hurt domestic firms abroad.',
    'Reporting omits the enforcement burden on customs infrastructure and the degree to which gray-market transshipment already bypasses comparable restrictions.',
    'Both frames are internally consistent; the decisive question is enforcement efficacy, which neither side of the coverage addresses with data.'
  ),
  'demo-semi-2': debateFor(
    'chip fabrication expansion',
    'Progressives highlight that expanded fabrication brings high-wage employment but worry the workforce pipeline and housing supply are being neglected.',
    'Conservatives emphasize permitting reform, reliable energy pricing, and a predictable tax environment as the conditions that determine whether expansion actually lands.',
    'Coverage omits the water and power constraints in the host regions, which are the binding constraints on real production timelines.',
    'The expansion story is accurate at a headline level but the coverage underweights infrastructure constraints that will shape the actual outcome.'
  ),
  // Climate / energy
  'demo-climate-1': debateFor(
    'carbon pricing policy',
    'Progressives argue carbon pricing must be paired with dividend programs so households are not left behind, and that revenue should accelerate grid decarbonization.',
    'Conservatives argue for market-based instruments over mandates, noting that pricing mechanisms can achieve emissions goals at lower economic cost than command-and-control rules.',
    'Analysis omits the international competitiveness dimension — jurisdictions without equivalent pricing shift production rather than reduce global emissions.',
    'The piece is balanced on domestic effects but the leakage problem is the analytical gap; without addressing it the policy case is incomplete.'
  ),
  'demo-climate-2': debateFor(
    'renewable grid integration',
    'Progressives see renewables growth as the core climate solution and urge faster interconnection reform and storage deployment to absorb the surge.',
    'Conservatives caution that reliability must lead, citing the need for firm power, grid upgrades, and honest accounting of backup costs.',
    'The coverage omits the interconnection queue — where projects now wait years — which is the single biggest bottleneck in the buildout.',
    'Factually strong, but the queue problem deserves the prominence the headline gives to capacity records.'
  ),
  // AI regulation
  'demo-ai-1': debateFor(
    'AI regulation framework',
    'Progressives want binding transparency and liability rules, arguing that voluntary commitments have not kept pace with deployment.',
    'Conservatives favor targeted, risk-based rules and warn that broad mandates would push development offshore and entrench incumbents.',
    'Both sides assume the framework is enforceable; coverage omits the state-federal patchwork and the absence of inspection capacity.',
    'The debate is well-framed but enforcement reality is the missing variable; neither frame confronts it directly.'
  ),
  'demo-ai-2': debateFor(
    'automation and labor markets',
    'Progressives emphasize retraining investment and income support as automation accelerates, warning of regional concentration of job losses.',
    'Conservatives point to historical productivity gains and argue flexible labor markets plus educational choice are the resilient response.',
    'Coverage omits the geographic concentration effect — losses are not spread evenly, and local labor markets matter far more than aggregates.',
    'The aggregate framing is defensible but the regional dimension is where the policy stakes actually live.'
  ),
  // Geopolitics / trade
  'demo-trade-1': debateFor(
    'trade agreement negotiations',
    'Progressives press for labor and environmental standards to be enforceable within the agreement, not side letters.',
    'Conservatives emphasize market access and dispute-resolution speed, cautioning that overloading agreements reduces their viability.',
    'Reporting omits the services and digital trade chapters, which will determine most of the economic impact in the coming decade.',
    'The coverage captures the politics accurately but misweights the economics: digital trade dwarfs the headline goods numbers.'
  ),
  'demo-trade-2': debateFor(
    'supply chain diversification',
    'Progressives frame diversification as resilience policy that also supports allied economies and better labor conditions.',
    'Conservatives frame it as strategic competition, prioritizing security of supply over cost minimization and pushing for faster permitting.',
    'The coverage omits cost pass-through to consumers and the timeline realities of building redundant capacity.',
    'The strategic framing is fair, but the cost question is treated as an afterthought when it will drive political sustainability.'
  ),
  // Health / science
  'demo-health-1': debateFor(
    'vaccine development news',
    'Progressives emphasize equitable global distribution and warn against intellectual-property barriers limiting access.',
    'Conservatives emphasize the scientific achievement and the role of private incentives in producing the breakthrough.',
    'Coverage omits the manufacturing scale-up constraints and cold-chain logistics that determine real-world access.',
    'The science reporting is accurate; the access question is where coverage needs more evidence, not more advocacy.'
  ),
  'demo-space-1': debateFor(
    'space exploration milestones',
    'Progressives see public investment in space as a driver of shared scientific progress and climate monitoring capability.',
    'Conservatives highlight commercial competition and argue private capital is now the marginal source of innovation.',
    'The coverage omits the budget trade-offs — every mission dollar competes with terrestrial science priorities.',
    'The milestone is real and well-reported; the funding-basis debate is legitimate but secondary to the achievement itself.'
  ),
  // Financial markets
  'demo-fin-1': debateFor(
    'market volatility',
    'Progressives argue volatility reflects fragile liquidity and call for structural reform of market plumbing and circuit breakers.',
    'Conservatives argue the pullback is a healthy repricing after a speculative run and oppose regulatory overreaction.',
    'Coverage omits the role of derivative positioning and the fact that realized volatility is regime-dependent, not regime-predicting.',
    'The market narrative is competent but over-determined; the honest takeaway is that near-term direction is unknowable.'
  ),
  'demo-fin-2': debateFor(
    'banking sector news',
    'Progressives urge tighter capital and liquidity rules and stress-testing of interest-rate risk.',
    'Conservatives argue the sector is well-capitalized and warn that heavier regulation would shrink credit availability.',
    'Coverage omits the duration-mismatch exposure that drove the last stress event — the exact mechanism that matters.',
    'The regulatory debate is legitimate, but reporting should anchor it in the balance-sheet mechanics that actually determine resilience.'
  ),
  // --- Expanded categories ---
  'demo-health-3': debateFor(
    'public health digital records',
    'Progressives celebrate interoperability gains but warn that data consolidation without strong privacy guardrails exposes vulnerable populations.',
    'Conservatives emphasize that digital records reduce medical errors and administrative costs, and that market-driven standards outperform mandates.',
    'Coverage omits the vendor lock-in problem — most health systems run on two or three dominant EHR platforms whose switching costs are enormous.',
    'The interoperability milestone is real but the vendor concentration is the structural risk that will determine whether patient benefit actually materializes.'
  ),
  'demo-climate-5': debateFor(
    'climate finance adaptation funding',
    'Progressives argue wealthy nations have a moral and legal obligation to fund adaptation in climate-vulnerable countries under the Loss and Damage framework.',
    'Conservatives caution that open-ended funding commitments lack accountability and that private capital mobilization is more efficient than direct transfers.',
    'Coverage omits the fact that most adaptation funding is still loans, not grants — adding to the debt burden of the countries most affected.',
    'The funding pledges are headline-grabbing but the grant-vs-loan composition is what determines whether this actually helps or deepens vulnerability.'
  ),
  'demo-sport-1': debateFor(
    'olympic doping controversy',
    'Progressives argue the anti-doping system must be independent of national federations to be credible, citing conflicts of interest.',
    'Conservatives stress due process rights for athletes and warn that rushed adjudication risks destroying careers over inconclusive evidence.',
    'Coverage omits the power asymmetry between the WADA apparatus and individual athletes from smaller nations who lack legal resources.',
    'Both frames have merit; the systemic issue is enforcement asymmetry — well-funded programs navigate rules while under-resourced athletes face the full weight of the system.'
  ),
  'demo-edu-1': debateFor(
    'university funding crisis',
    'Progressives frame declining public investment as the root cause, arguing that tuition increases are a downstream effect of state disinvestment.',
    'Conservatives point to administrative bloat and argue that universities must control costs before demanding more public money.',
    'Coverage omits the enrollment cliff — demographic shifts will reduce the student pool by 15% by 2030, threatening institutional viability regardless of funding.',
    'The cost and funding debate is valid but the demographic trajectory is the underexamined structural risk that will reshape the sector.'
  ),
  'demo-ent-1': debateFor(
    'streaming platform market consolidation',
    'Progressives warn that media consolidation reduces content diversity and gives a handful of tech companies outsized cultural influence.',
    'Conservatives argue that market competition drives innovation and that consumer choice — measured by subscriptions — proves the system works.',
    'Coverage omits the global dimension: non-US content markets are being reshaped by a few American platforms with little local regulatory input.',
    'The domestic competition frame is incomplete; the real story is how platform economics are reshaping cultural production worldwide.'
  ),
  'demo-geo-1': debateFor(
    'global migration policy reform',
    'Progressives call for expanded legal pathways and humane processing, arguing that enforcement-only approaches have failed for decades.',
    'Conservatives insist that border security must precede any reform, warning that amnesty incentives drive further irregular migration.',
    'Coverage omits the demographic driver — aging societies need working-age migrants to sustain pension and healthcare systems.',
    'The political debate is polarized but the demographic math is unambiguous: without migration, fiscal sustainability fails in most developed economies.'
  ),
};

// ---------------------------------------------------------------------------
// Article dataset — generic synthetic examples, never presented as real news.
// ---------------------------------------------------------------------------

const demoTimestamp = (hoursAgo: number) => new Date(now - hoursAgo * HOURS).toISOString();

const baseArticles: Array<Partial<Article> & { id: string; title: string; excerpt: string; sourceName: string; sourceCredibility: number; category: Article['category']; biasRating: Article['biasRating']; verificationStatus: Article['verificationStatus']; latitude: number; longitude: number; timestamp: string; url: string; debateKey: string; biasAxes: { Emotion: number; Omission: number; Framing: number } }> = [
  {
    id: 'demo-cb-1',
    title: 'Central bank holds rates steady as inflation cools, signals patience on easing',
    excerpt: 'Policymakers left the benchmark rate unchanged for a third consecutive meeting, citing gradual disinflation while keeping the door open for later cuts if data cooperates.',
    sourceName: 'Reuters World',
    sourceCredibility: 0.92,
    category: 'Business',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 51.5074,
    longitude: -0.1278,
    timestamp: demoTimestamp(2),
    url: 'https://www.reuters.com/',
    debateKey: 'demo-cb-1',
    biasAxes: { Emotion: 0.25, Omission: 0.45, Framing: 0.3 },
  },
  {
    id: 'demo-cb-2',
    title: 'Inflation data shows core pressures easing more slowly than headline',
    excerpt: 'The latest consumer price report beat expectations on the headline measure, but services inflation — led by shelter costs — remains sticky.',
    sourceName: 'Associated Press',
    sourceCredibility: 0.9,
    category: 'Business',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 40.7128,
    longitude: -74.006,
    timestamp: demoTimestamp(4),
    url: 'https://apnews.com/',
    debateKey: 'demo-cb-2',
    biasAxes: { Emotion: 0.2, Omission: 0.4, Framing: 0.35 },
  },
  {
    id: 'demo-semi-1',
    title: 'New export control regime targets advanced chipmaking equipment',
    excerpt: 'Authorities announced tightened restrictions on advanced lithography exports, citing national security concerns and supply chain integrity.',
    sourceName: 'Reuters World',
    sourceCredibility: 0.92,
    category: 'Tech',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 25.033,
    longitude: 121.5654,
    timestamp: demoTimestamp(3),
    url: 'https://www.reuters.com/',
    debateKey: 'demo-semi-1',
    biasAxes: { Emotion: 0.35, Omission: 0.5, Framing: 0.45 },
  },
  {
    id: 'demo-semi-2',
    title: 'Fabrication expansion projects face permitting and power bottlenecks',
    excerpt: 'Industry executives warn that multi-billion-dollar fab projects are slipping as interconnection queues and energy supply constraints bite.',
    sourceName: 'BBC News',
    sourceCredibility: 0.88,
    category: 'Tech',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 33.4484,
    longitude: -112.074,
    timestamp: demoTimestamp(6),
    url: 'https://www.bbc.com/news',
    debateKey: 'demo-semi-2',
    biasAxes: { Emotion: 0.3, Omission: 0.55, Framing: 0.4 },
  },
  {
    id: 'demo-climate-1',
    title: 'Carbon pricing proposal reignites debate over cost and fairness',
    excerpt: 'A proposed emissions-pricing scheme has split lawmakers, with supporters citing efficiency and critics warning of household cost burdens.',
    sourceName: 'NPR News',
    sourceCredibility: 0.85,
    category: 'Politics',
    biasRating: 'Center-Left',
    verificationStatus: 'VERIFIED',
    latitude: 48.8566,
    longitude: 2.3522,
    timestamp: demoTimestamp(8),
    url: 'https://www.npr.org/',
    debateKey: 'demo-climate-1',
    biasAxes: { Emotion: 0.55, Omission: 0.45, Framing: 0.5 },
  },
  {
    id: 'demo-climate-2',
    title: 'Renewable capacity hits record but grid interconnection lags behind',
    excerpt: 'New wind and solar installations reached an all-time high this quarter, while the queue of projects awaiting grid connection continues to grow.',
    sourceName: 'BBC News',
    sourceCredibility: 0.88,
    category: 'Science',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 52.52,
    longitude: 13.405,
    timestamp: demoTimestamp(10),
    url: 'https://www.bbc.com/news',
    debateKey: 'demo-climate-2',
    biasAxes: { Emotion: 0.35, Omission: 0.6, Framing: 0.45 },
  },
  {
    id: 'demo-ai-1',
    title: 'AI oversight framework advances as lawmakers weigh binding rules',
    excerpt: 'Negotiators are closing in on a cross-border framework for artificial intelligence, with enforcement mechanisms the final sticking point.',
    sourceName: 'Associated Press',
    sourceCredibility: 0.9,
    category: 'Tech',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 50.8503,
    longitude: 4.3517,
    timestamp: demoTimestamp(5),
    url: 'https://apnews.com/',
    debateKey: 'demo-ai-1',
    biasAxes: { Emotion: 0.3, Omission: 0.5, Framing: 0.4 },
  },
  {
    id: 'demo-ai-2',
    title: 'Automation forecasts sharpen focus on regional job displacement',
    excerpt: 'New analysis suggests automation-driven job changes will be felt unevenly across regions, intensifying calls for localized retraining programs.',
    sourceName: 'NPR News',
    sourceCredibility: 0.85,
    category: 'Tech',
    biasRating: 'Center-Left',
    verificationStatus: 'VERIFIED',
    latitude: 38.9072,
    longitude: -77.0369,
    timestamp: demoTimestamp(12),
    url: 'https://www.npr.org/',
    debateKey: 'demo-ai-2',
    biasAxes: { Emotion: 0.5, Omission: 0.5, Framing: 0.55 },
  },
  {
    id: 'demo-trade-1',
    title: 'Trade negotiators reach tentative deal on goods, digital chapters remain',
    excerpt: 'Negotiators announced progress on tariff schedules and market access, with services and digital trade provisions deferred to a second round.',
    sourceName: 'Reuters World',
    sourceCredibility: 0.92,
    category: 'Business',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: -33.8688,
    longitude: 151.2093,
    timestamp: demoTimestamp(7),
    url: 'https://www.reuters.com/',
    debateKey: 'demo-trade-1',
    biasAxes: { Emotion: 0.25, Omission: 0.5, Framing: 0.35 },
  },
  {
    id: 'demo-trade-2',
    title: 'Supply chain diversification gathers pace as firms rebalance sourcing',
    excerpt: 'Manufacturers are accelerating plans to build redundant sourcing networks, though executives flag cost and timeline pressures.',
    sourceName: 'BBC News',
    sourceCredibility: 0.88,
    category: 'Business',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 1.3521,
    longitude: 103.8198,
    timestamp: demoTimestamp(9),
    url: 'https://www.bbc.com/news',
    debateKey: 'demo-trade-2',
    biasAxes: { Emotion: 0.3, Omission: 0.55, Framing: 0.4 },
  },
  {
    id: 'demo-health-1',
    title: 'Trial results show promise for next-generation vaccine candidates',
    excerpt: 'Interim data from a late-stage trial suggests strong efficacy, with distribution and cold-chain logistics now the focus of planning.',
    sourceName: 'Associated Press',
    sourceCredibility: 0.9,
    category: 'Science',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: -1.2921,
    longitude: 36.8219,
    timestamp: demoTimestamp(14),
    url: 'https://apnews.com/',
    debateKey: 'demo-health-1',
    biasAxes: { Emotion: 0.4, Omission: 0.45, Framing: 0.35 },
  },
  {
    id: 'demo-space-1',
    title: 'Space agency confirms new orbital milestone as commercial missions expand',
    excerpt: 'Agency officials confirmed the successful deployment of a new observation platform, underscoring the growing role of commercial partners.',
    sourceName: 'BBC News',
    sourceCredibility: 0.88,
    category: 'Science',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 28.5729,
    longitude: -80.649,
    timestamp: demoTimestamp(16),
    url: 'https://www.bbc.com/news',
    debateKey: 'demo-space-1',
    biasAxes: { Emotion: 0.45, Omission: 0.3, Framing: 0.3 },
  },
  {
    id: 'demo-fin-1',
    title: 'Markets slide as volatility returns after extended rally',
    excerpt: 'Equity markets pulled back sharply this week as investors repriced expectations, with analysts split on whether the correction has further to run.',
    sourceName: 'Reuters World',
    sourceCredibility: 0.92,
    category: 'Business',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 40.7128,
    longitude: -74.006,
    timestamp: demoTimestamp(1),
    url: 'https://www.reuters.com/',
    debateKey: 'demo-fin-1',
    biasAxes: { Emotion: 0.5, Omission: 0.4, Framing: 0.45 },
  },
  {
    id: 'demo-fin-2',
    title: 'Banking sector faces renewed scrutiny over balance-sheet exposure',
    excerpt: 'Regulators are examining duration risk across the sector after a series of stress tests flagged sensitivity to sharp rate moves.',
    sourceName: 'Associated Press',
    sourceCredibility: 0.9,
    category: 'Business',
    biasRating: 'Center',
    verificationStatus: 'MISLEADING',
    latitude: 51.5074,
    longitude: -0.1278,
    timestamp: demoTimestamp(11),
    url: 'https://apnews.com/',
    debateKey: 'demo-fin-2',
    biasAxes: { Emotion: 0.6, Omission: 0.6, Framing: 0.65 },
  },
  {
    id: 'demo-cb-3',
    title: 'Rate cut expectations shift after hawkish comments from policymakers',
    excerpt: 'Comments from central bank officials dampened near-term easing bets, sending bond yields higher and currency markets into a quiet repricing.',
    sourceName: 'Reuters World',
    sourceCredibility: 0.92,
    category: 'Business',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 35.6762,
    longitude: 139.6503,
    timestamp: demoTimestamp(13),
    url: 'https://www.reuters.com/',
    debateKey: 'demo-cb-1',
    biasAxes: { Emotion: 0.3, Omission: 0.45, Framing: 0.4 },
  },
  {
    id: 'demo-trade-3',
    title: 'Port congestion eases as shipping volumes normalize after holiday surge',
    excerpt: 'Major ports reported improved dwell times this month as container volumes returned to seasonal norms, relieving pressure on freight rates.',
    sourceName: 'BBC News',
    sourceCredibility: 0.88,
    category: 'Business',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 22.5431,
    longitude: 114.0579,
    timestamp: demoTimestamp(18),
    url: 'https://www.bbc.com/news',
    debateKey: 'demo-trade-2',
    biasAxes: { Emotion: 0.2, Omission: 0.35, Framing: 0.3 },
  },
  {
    id: 'demo-climate-3',
    title: 'Extreme weather events drive fresh calls for adaptation funding',
    excerpt: 'A new assessment links recent extreme weather patterns to rising adaptation costs, intensifying negotiations over climate finance.',
    sourceName: 'NPR News',
    sourceCredibility: 0.85,
    category: 'Politics',
    biasRating: 'Center-Left',
    verificationStatus: 'VERIFIED',
    latitude: -23.5505,
    longitude: -46.6333,
    timestamp: demoTimestamp(20),
    url: 'https://www.npr.org/',
    debateKey: 'demo-climate-1',
    biasAxes: { Emotion: 0.6, Omission: 0.4, Framing: 0.55 },
  },
  {
    id: 'demo-ai-3',
    title: 'Researchers publish new benchmark for evaluating model transparency',
    excerpt: 'A coalition of researchers released an open benchmark measuring how clearly AI systems disclose their training data and limitations.',
    sourceName: 'NPR News',
    sourceCredibility: 0.85,
    category: 'Tech',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 37.7749,
    longitude: -122.4194,
    timestamp: demoTimestamp(22),
    url: 'https://www.npr.org/',
    debateKey: 'demo-ai-1',
    biasAxes: { Emotion: 0.25, Omission: 0.45, Framing: 0.35 },
  },
  {
    id: 'demo-health-2',
    title: 'Public health officials publish updated guidance on seasonal illness',
    excerpt: 'Updated guidance reflects new surveillance data, with officials emphasizing early vaccination windows and strain-matched formulations.',
    sourceName: 'Associated Press',
    sourceCredibility: 0.9,
    category: 'Science',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: -33.8688,
    longitude: 151.2093,
    timestamp: demoTimestamp(24),
    url: 'https://apnews.com/',
    debateKey: 'demo-health-1',
    biasAxes: { Emotion: 0.3, Omission: 0.3, Framing: 0.3 },
  },
  {
    id: 'demo-fin-3',
    title: 'Bond yields climb as investors digest fresh issuance calendar',
    excerpt: 'Treasury markets absorbed a heavy week of issuance, with longer-dated yields drifting higher amid steady demand.',
    sourceName: 'Reuters World',
    sourceCredibility: 0.92,
    category: 'Business',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 51.5074,
    longitude: -0.1278,
    timestamp: demoTimestamp(26),
    url: 'https://www.reuters.com/',
    debateKey: 'demo-fin-1',
    biasAxes: { Emotion: 0.2, Omission: 0.4, Framing: 0.35 },
  },
  {
    id: 'demo-semi-3',
    title: 'Chipmakers ramp memory output as data-center demand stays strong',
    excerpt: 'Memory manufacturers are expanding capacity to meet sustained demand from data centers, though pricing remains competitive.',
    sourceName: 'BBC News',
    sourceCredibility: 0.88,
    category: 'Tech',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 37.5665,
    longitude: 126.978,
    timestamp: demoTimestamp(28),
    url: 'https://www.bbc.com/news',
    debateKey: 'demo-semi-1',
    biasAxes: { Emotion: 0.25, Omission: 0.4, Framing: 0.35 },
  },
  {
    id: 'demo-trade-4',
    title: 'Currency markets steady as exporters adjust to new tariff schedule',
    excerpt: 'Export-oriented economies are adapting to the revised tariff schedule, with currency markets trading in narrow ranges.',
    sourceName: 'Reuters World',
    sourceCredibility: 0.92,
    category: 'Business',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 19.076,
    longitude: 72.8777,
    timestamp: demoTimestamp(30),
    url: 'https://www.reuters.com/',
    debateKey: 'demo-trade-1',
    biasAxes: { Emotion: 0.2, Omission: 0.45, Framing: 0.35 },
  },
  {
    id: 'demo-climate-4',
    title: 'Coastal cities unveil joint resilience plans for rising sea levels',
    excerpt: 'A coalition of coastal cities announced coordinated infrastructure investments aimed at hardening against rising sea levels.',
    sourceName: 'NPR News',
    sourceCredibility: 0.85,
    category: 'Politics',
    biasRating: 'Center-Left',
    verificationStatus: 'VERIFIED',
    latitude: 1.3521,
    longitude: 103.8198,
    timestamp: demoTimestamp(32),
    url: 'https://www.npr.org/',
    debateKey: 'demo-climate-2',
    biasAxes: { Emotion: 0.5, Omission: 0.4, Framing: 0.5 },
  },
  {
    id: 'demo-ai-4',
    title: 'AI adoption in healthcare accelerates, raising new oversight questions',
    excerpt: 'Deployment of clinical AI tools is rising quickly, prompting regulators and clinicians to press for clearer evaluation standards.',
    sourceName: 'Associated Press',
    sourceCredibility: 0.9,
    category: 'Tech',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 34.0522,
    longitude: -118.2437,
    timestamp: demoTimestamp(34),
    url: 'https://apnews.com/',
    debateKey: 'demo-ai-2',
    biasAxes: { Emotion: 0.35, Omission: 0.5, Framing: 0.4 },
  },
  {
    id: 'demo-health-3',
    title: 'Health systems report progress on digitizing patient records',
    excerpt: 'Interoperability efforts are yielding measurable progress, though smaller providers still lag on data-sharing readiness.',
    sourceName: 'BBC News',
    sourceCredibility: 0.88,
    category: 'Science',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 51.5074,
    longitude: -0.1278,
    timestamp: demoTimestamp(36),
    url: 'https://www.bbc.com/news',
    debateKey: 'demo-health-1',
    biasAxes: { Emotion: 0.3, Omission: 0.35, Framing: 0.3 },
  },
  {
    id: 'demo-space-2',
    title: 'Satellite operators expand earth-observation coverage for climate monitoring',
    excerpt: 'New satellite deployments are filling gaps in global climate monitoring, improving detection of methane and land-use changes.',
    sourceName: 'NPR News',
    sourceCredibility: 0.85,
    category: 'Science',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: -13.1339,
    longitude: -72.5494,
    timestamp: demoTimestamp(38),
    url: 'https://www.npr.org/',
    debateKey: 'demo-space-1',
    biasAxes: { Emotion: 0.35, Omission: 0.3, Framing: 0.3 },
  },
  {
    id: 'demo-fin-4',
    title: 'Earnings season shows corporate margins holding up despite cost pressure',
    excerpt: 'Early earnings reports point to resilient margins, with companies passing through costs and guiding cautiously for the quarters ahead.',
    sourceName: 'Reuters World',
    sourceCredibility: 0.92,
    category: 'Business',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 40.7128,
    longitude: -74.006,
    timestamp: demoTimestamp(40),
    url: 'https://www.reuters.com/',
    debateKey: 'demo-fin-2',
    biasAxes: { Emotion: 0.25, Omission: 0.4, Framing: 0.35 },
  },
  // --- Story-tracker demo stories: these deliberately overlap in topic so the
  // clustering engine forms corroborated multi-source stories. ---
  {
    id: 'demo-cb-4',
    title: 'Central banks signal coordinated path on interest rates as inflation cools',
    excerpt: 'Officials across major economies indicated a patient approach to policy, wary of easing too quickly while disinflation remains uneven.',
    sourceName: 'Associated Press',
    sourceCredibility: 0.9,
    category: 'Business',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 40.7128,
    longitude: -74.006,
    timestamp: demoTimestamp(15),
    url: 'https://apnews.com/',
    debateKey: 'demo-cb-1',
    biasAxes: { Emotion: 0.25, Omission: 0.45, Framing: 0.35 },
  },
  {
    id: 'demo-cb-5',
    title: 'Global rate-setters converge on patient easing stance',
    excerpt: 'Policymakers across major economies are aligning on a patient approach to interest rates, wary of premature cuts as data firms up.',
    sourceName: 'BBC News',
    sourceCredibility: 0.88,
    category: 'Business',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 51.5074,
    longitude: -0.1278,
    timestamp: demoTimestamp(17),
    url: 'https://www.bbc.com/news',
    debateKey: 'demo-cb-2',
    biasAxes: { Emotion: 0.2, Omission: 0.4, Framing: 0.3 },
  },
  {
    id: 'demo-semi-4',
    title: 'Export controls on advanced chip tools draw industry response',
    excerpt: 'Semiconductor makers pushed back on the scope of the new export restrictions, warning of compliance costs and supply chain friction.',
    sourceName: 'Associated Press',
    sourceCredibility: 0.9,
    category: 'Tech',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 40.7128,
    longitude: -74.006,
    timestamp: demoTimestamp(19),
    url: 'https://apnews.com/',
    debateKey: 'demo-semi-1',
    biasAxes: { Emotion: 0.35, Omission: 0.5, Framing: 0.45 },
  },
  {
    id: 'demo-semi-5',
    title: 'Lawmakers push for tighter chip export controls',
    excerpt: 'A bipartisan group is pressing for stricter limits on advanced chip exports, citing supply chain security concerns in the current regime.',
    sourceName: 'NPR News',
    sourceCredibility: 0.85,
    category: 'Tech',
    biasRating: 'Center-Left',
    verificationStatus: 'VERIFIED',
    latitude: 38.9072,
    longitude: -77.0369,
    timestamp: demoTimestamp(21),
    url: 'https://www.npr.org/',
    debateKey: 'demo-semi-2',
    biasAxes: { Emotion: 0.4, Omission: 0.5, Framing: 0.45 },
  },
  {
    id: 'demo-climate-5',
    title: 'Climate finance talks intensify after extreme weather season',
    excerpt: 'A punishing extreme weather season has sharpened the push for adaptation funding as negotiators reopen climate finance commitments.',
    sourceName: 'BBC News',
    sourceCredibility: 0.88,
    category: 'Politics',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 52.52,
    longitude: 13.405,
    timestamp: demoTimestamp(23),
    url: 'https://www.bbc.com/news',
    debateKey: 'demo-climate-1',
    biasAxes: { Emotion: 0.55, Omission: 0.4, Framing: 0.5 },
  },
  {
    id: 'demo-climate-6',
    title: 'Coastal resilience funding tops climate agenda',
    excerpt: 'Coastal governments are pressing for dedicated resilience funding as rising sea levels force hard infrastructure choices.',
    sourceName: 'Reuters World',
    sourceCredibility: 0.92,
    category: 'Politics',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 25.2048,
    longitude: 55.2708,
    timestamp: demoTimestamp(25),
    url: 'https://www.reuters.com/',
    debateKey: 'demo-climate-2',
    biasAxes: { Emotion: 0.5, Omission: 0.4, Framing: 0.5 },
  },
  // --- Expanded: Health / Science (more sources) ---
  {
    id: 'demo-health-4',
    title: 'Universal health records platform gains traction across European systems',
    excerpt: 'A new interoperability standard is enabling cross-border patient data sharing, though privacy advocates raise concerns about consent protocols.',
    sourceName: 'Financial Times',
    sourceCredibility: 0.88,
    category: 'Science',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 51.5074,
    longitude: -0.1278,
    timestamp: demoTimestamp(5),
    url: 'https://www.ft.com/',
    debateKey: 'demo-health-3',
    biasAxes: { Emotion: 0.35, Omission: 0.5, Framing: 0.4 },
  },
  {
    id: 'demo-health-5',
    title: 'WHO declares new mpox variant a public health emergency',
    excerpt: 'The World Health Organization raised its alert level after cases surged across central Africa and spread to non-endemic countries.',
    sourceName: 'Al Jazeera',
    sourceCredibility: 0.82,
    category: 'Science',
    biasRating: 'Center-Left',
    verificationStatus: 'VERIFIED',
    latitude: 1.2921,
    longitude: 36.8219,
    timestamp: demoTimestamp(8),
    url: 'https://www.aljazeera.com/',
    debateKey: 'demo-health-1',
    biasAxes: { Emotion: 0.55, Omission: 0.45, Framing: 0.5 },
  },
  // --- Climate / Environment (expanded) ---
  {
    id: 'demo-climate-7',
    title: 'Wealthy nations pledge $300B annually for climate adaptation in Global South',
    excerpt: 'Negotiators agreed on a new funding target, though developing nations say the amount falls far short of the trillions needed.',
    sourceName: 'Deutsche Welle',
    sourceCredibility: 0.85,
    category: 'Politics',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 50.7359,
    longitude: 7.1007,
    timestamp: demoTimestamp(11),
    url: 'https://www.dw.com/',
    debateKey: 'demo-climate-5',
    biasAxes: { Emotion: 0.5, Omission: 0.55, Framing: 0.5 },
  },
  {
    id: 'demo-climate-8',
    title: 'Amazon deforestation drops 40% under new enforcement regime',
    excerpt: 'Satellite monitoring and increased enforcement have driven a sharp decline in illegal clearing, though illegal mining persists.',
    sourceName: 'Reuters World',
    sourceCredibility: 0.92,
    category: 'Science',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: -3.0,
    longitude: -60.0,
    timestamp: demoTimestamp(15),
    url: 'https://www.reuters.com/',
    debateKey: 'demo-climate-2',
    biasAxes: { Emotion: 0.3, Omission: 0.4, Framing: 0.35 },
  },
  // --- Sports ---
  {
    id: 'demo-sport-1',
    title: 'Olympic committee faces backlash over handling of doping allegations',
    excerpt: 'Multiple national federations have criticized the independent testing body for inconsistent enforcement and lack of transparency.',
    sourceName: 'BBC News',
    sourceCredibility: 0.88,
    category: 'Sports',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 48.8566,
    longitude: 2.3522,
    timestamp: demoTimestamp(6),
    url: 'https://www.bbc.com/news',
    debateKey: 'demo-sport-1',
    biasAxes: { Emotion: 0.5, Omission: 0.4, Framing: 0.45 },
  },
  {
    id: 'demo-sport-2',
    title: 'Women’s World Cup viewership shatters records across all platforms',
    excerpt: 'Broadcast and streaming numbers exceeded expectations, sparking renewed investment in women’s professional leagues globally.',
    sourceName: 'Associated Press',
    sourceCredibility: 0.9,
    category: 'Sports',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: -33.8688,
    longitude: 151.2093,
    timestamp: demoTimestamp(10),
    url: 'https://apnews.com/',
    debateKey: 'demo-sport-1',
    biasAxes: { Emotion: 0.4, Omission: 0.3, Framing: 0.35 },
  },
  // --- Education ---
  {
    id: 'demo-edu-1',
    title: 'University enrollment decline accelerates as demographic cliff approaches',
    excerpt: 'Colleges across the US and Europe are merging or closing as the pool of 18-year-olds shrinks, raising questions about institutional survival.',
    sourceName: 'NPR News',
    sourceCredibility: 0.85,
    category: 'Education',
    biasRating: 'Center-Left',
    verificationStatus: 'VERIFIED',
    latitude: 42.3601,
    longitude: -71.0589,
    timestamp: demoTimestamp(14),
    url: 'https://www.npr.org/',
    debateKey: 'demo-edu-1',
    biasAxes: { Emotion: 0.45, Omission: 0.5, Framing: 0.45 },
  },
  {
    id: 'demo-edu-2',
    title: 'AI tutoring tools show measurable gains in student outcomes',
    excerpt: 'A large-scale study found personalized AI tutors improved test scores by 12% on average, though researchers warn about equity gaps.',
    sourceName: 'The Conversation',
    sourceCredibility: 0.83,
    category: 'Education',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: -37.8136,
    longitude: 144.9631,
    timestamp: demoTimestamp(18),
    url: 'https://theconversation.com/',
    debateKey: 'demo-ai-2',
    biasAxes: { Emotion: 0.3, Omission: 0.45, Framing: 0.35 },
  },
  // --- Entertainment / Culture ---
  {
    id: 'demo-ent-1',
    title: 'Streaming giants consolidate as smaller platforms fold under content costs',
    excerpt: 'Three companies now control 70% of global streaming subscriptions, raising concerns about content diversity and pricing power.',
    sourceName: 'Financial Times',
    sourceCredibility: 0.88,
    category: 'Entertainment',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 40.7128,
    longitude: -74.006,
    timestamp: demoTimestamp(7),
    url: 'https://www.ft.com/',
    debateKey: 'demo-ent-1',
    biasAxes: { Emotion: 0.35, Omission: 0.45, Framing: 0.4 },
  },
  {
    id: 'demo-ent-2',
    title: 'Hollywood writers reach deal on AI use in scriptwriting',
    excerpt: 'The new contract establishes guardrails on AI-assisted content while preserving human creative control, setting a precedent for other industries.',
    sourceName: 'NBC News',
    sourceCredibility: 0.78,
    category: 'Entertainment',
    biasRating: 'Center-Left',
    verificationStatus: 'VERIFIED',
    latitude: 34.0522,
    longitude: -118.2437,
    timestamp: demoTimestamp(12),
    url: 'https://www.nbcnews.com/',
    debateKey: 'demo-ai-1',
    biasAxes: { Emotion: 0.45, Omission: 0.4, Framing: 0.4 },
  },
  // --- Geopolitics (new sources) ---
  {
    id: 'demo-geo-1',
    title: 'Record 120 million people forcibly displaced worldwide, UNHCR reports',
    excerpt: 'War, persecution, and climate-driven disasters have pushed displacement to unprecedented levels, straining host countries and aid systems.',
    sourceName: 'Al Jazeera',
    sourceCredibility: 0.82,
    category: 'Politics',
    biasRating: 'Center-Left',
    verificationStatus: 'VERIFIED',
    latitude: 32.05,
    longitude: 34.75,
    timestamp: demoTimestamp(4),
    url: 'https://www.aljazeera.com/',
    debateKey: 'demo-geo-1',
    biasAxes: { Emotion: 0.6, Omission: 0.45, Framing: 0.55 },
  },
  {
    id: 'demo-geo-2',
    title: 'EU approves sweeping migration pact after years of negotiation',
    excerpt: 'The new framework redistributes asylum processing across member states, though critics say it outsources border control to third countries.',
    sourceName: 'Euronews',
    sourceCredibility: 0.80,
    category: 'Politics',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 50.8503,
    longitude: 4.3517,
    timestamp: demoTimestamp(9),
    url: 'https://www.euronews.com/',
    debateKey: 'demo-geo-1',
    biasAxes: { Emotion: 0.45, Omission: 0.5, Framing: 0.45 },
  },
  // --- Asia-Pacific (new sources) ---
  {
    id: 'demo-asia-1',
    title: 'India overtakes Japan as world’s fourth-largest economy',
    excerpt: 'IMF data confirms India’s nominal GDP has surpassed Japan’s, driven by domestic consumption and services growth, though per-capita income remains low.',
    sourceName: 'The Hindu',
    sourceCredibility: 0.83,
    category: 'Business',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 13.0827,
    longitude: 80.2707,
    timestamp: demoTimestamp(3),
    url: 'https://www.thehindu.com/',
    debateKey: 'demo-trade-1',
    biasAxes: { Emotion: 0.35, Omission: 0.4, Framing: 0.3 },
  },
  {
    id: 'demo-asia-2',
    title: 'Hong Kong tensions rise as new national security charges filed',
    excerpt: 'Authorities filed charges under expanded security laws against pro-democracy activists, drawing condemnation from Western governments.',
    sourceName: 'South China Morning Post',
    sourceCredibility: 0.80,
    category: 'Politics',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: 22.3193,
    longitude: 114.1694,
    timestamp: demoTimestamp(6),
    url: 'https://www.scmp.com/',
    debateKey: 'demo-trade-2',
    biasAxes: { Emotion: 0.5, Omission: 0.55, Framing: 0.5 },
  },
  // --- Africa (new sources) ---
  {
    id: 'demo-africa-1',
    title: 'African Union launches continental free trade digital platform',
    excerpt: 'The digital marketplace aims to connect SMEs across 55 member states, though infrastructure gaps and tariff disputes remain obstacles.',
    sourceName: 'Daily Maverick',
    sourceCredibility: 0.81,
    category: 'Business',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: -33.9249,
    longitude: 18.4241,
    timestamp: demoTimestamp(13),
    url: 'https://www.dailymaverick.co.za/',
    debateKey: 'demo-trade-1',
    biasAxes: { Emotion: 0.3, Omission: 0.45, Framing: 0.35 },
  },
  {
    id: 'demo-africa-2',
    title: 'Kenya becomes East Africa’s geothermal energy leader',
    excerpt: 'New capacity additions make Kenya the continent’s largest geothermal producer, powering homes and attracting green investment.',
    sourceName: 'The East African',
    sourceCredibility: 0.77,
    category: 'Science',
    biasRating: 'Center',
    verificationStatus: 'VERIFIED',
    latitude: -1.2921,
    longitude: 36.8219,
    timestamp: demoTimestamp(16),
    url: 'https://www.theeastafrican.co.ke/',
    debateKey: 'demo-climate-2',
    biasAxes: { Emotion: 0.35, Omission: 0.3, Framing: 0.3 },
  },
  // --- Investigative (new sources) ---
  {
    id: 'demo-invest-1',
    title: 'Pandemic-era fraud cost taxpayers $200B, federal audit finds',
    excerpt: 'A sweeping investigation reveals systemic gaps in emergency lending programs that enabled widespread fraudulent claims.',
    sourceName: 'ProPublica',
    sourceCredibility: 0.87,
    category: 'Politics',
    biasRating: 'Center-Left',
    verificationStatus: 'VERIFIED',
    latitude: 40.7128,
    longitude: -74.006,
    timestamp: demoTimestamp(2),
    url: 'https://www.propublica.org/',
    debateKey: 'demo-fin-2',
    biasAxes: { Emotion: 0.45, Omission: 0.5, Framing: 0.4 },
  },
  {
    id: 'demo-invest-2',
    title: 'Pharmaceutical pricing investigation reveals hidden rebate schemes',
    excerpt: 'ProPublica analysis shows drug manufacturers use complex rebate structures to inflate list prices while appearing to offer discounts.',
    sourceName: 'ProPublica',
    sourceCredibility: 0.87,
    category: 'Science',
    biasRating: 'Center-Left',
    verificationStatus: 'VERIFIED',
    latitude: 38.9072,
    longitude: -77.0369,
    timestamp: demoTimestamp(8),
    url: 'https://www.propublica.org/',
    debateKey: 'demo-health-1',
    biasAxes: { Emotion: 0.5, Omission: 0.5, Framing: 0.45 },
  },
];

// Convert to full Article objects with per-article debate analysis attached.
export const demoArticles: Article[] = baseArticles.map((a) => {
  const debate = debates[a.debateKey] || debates['demo-cb-1'];
  return {
    id: a.id,
    title: a.title,
    excerpt: a.excerpt,
    content: a.excerpt,
    category: a.category,
    sourceName: a.sourceName,
    sourceCredibility: a.sourceCredibility,
    biasRating: a.biasRating,
    verificationStatus: a.verificationStatus,
    timestamp: a.timestamp,
    latitude: a.latitude,
    longitude: a.longitude,
    url: a.url,
    biasAxes: a.biasAxes,
    biasAnalysis: {
      progressive: { text: debate.progressive, label: 'Progressive' },
      conservative: { text: debate.conservative, label: 'Conservative' },
      omission: { text: debate.omissionFocused, label: 'Omission' },
      moderator: { text: debate.moderatorVerdict, label: 'Moderator' },
    },
    verificationTier: 'deep',
    verifiedBy: 'classical-ml',
    aiInsight: debate.moderatorVerdict,
    groundingUrls: [
      { uri: a.url, title: a.sourceName },
    ],
  };
});

// ---------------------------------------------------------------------------
// Source roster for the Source Directory view.
// ---------------------------------------------------------------------------

export const demoSources: Source[] = [
  {
    id: 'src-reuters',
    name: 'Reuters World',
    credibility: 92,
    biasRating: 'Center',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'International Wire',
    verifiedCount: 1240,
    flaggedCount: 8,
    description: 'Global news agency providing fast, factual reporting across markets, politics, and world events with rigorous sourcing standards.',
  },
  {
    id: 'src-ap',
    name: 'Associated Press',
    credibility: 90,
    biasRating: 'Center',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'International Wire',
    verifiedCount: 1187,
    flaggedCount: 12,
    description: 'Independent global news cooperative with a century of standards-driven journalism and wide syndication footprint.',
  },
  {
    id: 'src-bbc',
    name: 'BBC News',
    credibility: 86,
    biasRating: 'Center',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'Public Broadcaster',
    verifiedCount: 980,
    flaggedCount: 24,
    description: 'Public service broadcaster with global bureaus and a distinctive editorial voice, funded by license fee rather than advertising.',
  },
  {
    id: 'src-npr',
    name: 'NPR News',
    credibility: 85,
    biasRating: 'Center-Left',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'Public Radio',
    verifiedCount: 762,
    flaggedCount: 19,
    description: 'American public radio network known for long-form reporting and analysis, with member-station local partnerships.',
  },
  {
    id: 'src-ft',
    name: 'Financial Times',
    credibility: 88,
    biasRating: 'Center',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'Business Daily',
    verifiedCount: 854,
    flaggedCount: 15,
    description: 'International business newspaper with deep corporate, markets, and policy coverage and strong fact-checking culture.',
  },
  {
    id: 'src-bloomberg',
    name: 'Bloomberg',
    credibility: 87,
    biasRating: 'Center',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'Financial Data & News',
    verifiedCount: 911,
    flaggedCount: 17,
    description: 'Global financial data and news organization with unmatched markets coverage and terminal-based data infrastructure.',
  },
  {
    id: 'src-aj',
    name: 'Al Jazeera',
    credibility: 82,
    biasRating: 'Center-Left',
    verificationStatus: 'Partially Provenance-Clear',
    category: 'International Broadcaster',
    verifiedCount: 640,
    flaggedCount: 31,
    description: 'Doha-based international news network with strong Middle East and Global South coverage and distinctive regional sourcing.',
  },
  {
    id: 'src-guardian',
    name: 'The Guardian',
    credibility: 84,
    biasRating: 'Center-Left',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'Broadsheet',
    verifiedCount: 703,
    flaggedCount: 28,
    description: 'UK-based open-access newspaper with investigative strength and explicitly progressive editorial stance on many topics.',
  },
  {
    id: 'src-wsj',
    name: 'Wall Street Journal',
    credibility: 89,
    biasRating: 'Center-Right',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'Business Daily',
    verifiedCount: 876,
    flaggedCount: 14,
    description: 'US business daily with rigorous reporting and an editorial page separate from its newsroom, known for markets depth.',
  },
  {
    id: 'src-fox',
    name: 'Fox News',
    credibility: 61,
    biasRating: 'Right',
    verificationStatus: 'Partially Provenance-Clear',
    category: 'Cable News',
    verifiedCount: 312,
    flaggedCount: 142,
    description: 'US cable news network with a strongly conservative framing across political coverage and opinion-heavy programming.',
  },
  {
    id: 'src-aeon',
    name: 'Euronews',
    credibility: 80,
    biasRating: 'Center',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'Pan-European Broadcaster',
    verifiedCount: 520,
    flaggedCount: 18,
    description: 'Pan-European news network covering EU politics, business, and culture with a multilingual editorial approach.',
  },
  {
    id: 'src-dw',
    name: 'Deutsche Welle',
    credibility: 85,
    biasRating: 'Center',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'International Broadcaster',
    verifiedCount: 680,
    flaggedCount: 14,
    description: 'German public international broadcaster with global reach in 30+ languages, known for analytical long-form coverage.',
  },
  {
    id: 'src-hindu',
    name: 'The Hindu',
    credibility: 83,
    biasRating: 'Center',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'Broadsheet',
    verifiedCount: 640,
    flaggedCount: 22,
    description: 'India’s leading English-language broadsheet with strong editorial standards and in-depth South Asian coverage.',
  },
  {
    id: 'src-scmp',
    name: 'South China Morning Post',
    credibility: 80,
    biasRating: 'Center',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'Business Daily',
    verifiedCount: 580,
    flaggedCount: 26,
    description: 'Hong Kong-based English-language newspaper with authoritative China and Asia-Pacific business and political coverage.',
  },
  {
    id: 'src-prop',
    name: 'ProPublica',
    credibility: 87,
    biasRating: 'Center-Left',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'Investigative',
    verifiedCount: 420,
    flaggedCount: 6,
    description: 'Nonprofit investigative journalism newsroom producing high-impact accountability reporting on corruption and abuse of power.',
  },
  {
    id: 'src-conversation',
    name: 'The Conversation',
    credibility: 83,
    biasRating: 'Center',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'Academic Journalism',
    verifiedCount: 380,
    flaggedCount: 8,
    description: 'Expert-written articles by academics and researchers, translating complex research into accessible news with full source disclosure.',
  },
  {
    id: 'src-dm',
    name: 'Daily Maverick',
    credibility: 81,
    biasRating: 'Center-Left',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'Investigative',
    verifiedCount: 310,
    flaggedCount: 12,
    description: 'South Africa’s leading independent investigative newsroom covering corruption, governance, and social justice across the continent.',
  },
  {
    id: 'src-te',
    name: 'The East African',
    credibility: 77,
    biasRating: 'Center',
    verificationStatus: 'Partially Provenance-Clear',
    category: 'Regional Weekly',
    verifiedCount: 240,
    flaggedCount: 18,
    description: 'Nairobi-based regional newspaper covering East African business, politics, and development with a pan-African editorial lens.',
  },
  {
    id: 'src-ms',
    name: 'MercoPress',
    credibility: 78,
    biasRating: 'Center',
    verificationStatus: 'Partially Provenance-Clear',
    category: 'Regional Wire',
    verifiedCount: 290,
    flaggedCount: 15,
    description: 'English-language news service covering Mercosur countries and Latin American politics, economics, and trade.',
  },
  {
    id: 'src-nature',
    name: 'Nature News',
    credibility: 91,
    biasRating: 'Center',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'Science',
    verifiedCount: 560,
    flaggedCount: 3,
    description: 'The news arm of the world’s leading scientific journal, covering breakthroughs, policy, and the business of science.',
  },
  {
    id: 'src-lancet',
    name: 'The Lancet',
    credibility: 89,
    biasRating: 'Center',
    verificationStatus: 'Fully Provenance-Clear',
    category: 'Medical Journal',
    verifiedCount: 480,
    flaggedCount: 4,
    description: 'Leading global medical journal publishing research, reviews, and commentary on public health and clinical medicine.',
  },
];

// ---------------------------------------------------------------------------
// Business-intelligence demo data (used to power the chart + registry).
// ---------------------------------------------------------------------------

export const demoTransparencyTrend = Array.from({ length: 30 }, (_, i) => {
  const day = new Date(now - (29 - i) * DAYS);
  const base = 70 + Math.sin(i / 3.2) * 8 + (i % 5) * 1.4;
  return {
    date: day.toISOString().slice(0, 10),
    volume: Math.round(base * 1.7),
    credibility: Math.min(96, Math.max(64, base)),
  };
});

export const demoForecastProjection = Array.from({ length: 30 }, (_, i) => {
  const day = new Date(now + (i + 1) * DAYS);
  const base = 78 + Math.sin((i + 30) / 3.5) * 6 + i * 0.35;
  return {
    date: day.toISOString().slice(0, 10),
    volume: Math.round(base * 1.7),
    credibility: Math.min(96, Math.max(64, base)),
  };
});

export const demoForecastSummary =
  'Projection: transparency filing volume is expected to climb ~9% over the next 30 days, tracking the current policy-registration cycle, while aggregate source credibility holds in the 78–86 band. Watch the interconnection-queue and export-regime stories — they are the two highest-volatility narratives in the pipeline.';
